import type { Metadata } from "next";
import "./globals.scss";
import LayoutClient from "./layout.c";

export const metadata: Metadata = {
  title: "Video Recorder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LayoutClient>{children}</LayoutClient>
      </body>
    </html>
  );
}
